name: Update Saved Tracks

on:
  workflow_dispatch:        

permissions:
  contents: write    


env:
  ACTIONS_STEP_DEBUG: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone the Python script repo
        run: |
          git clone https://github.com/hevannder/get-spotify.git external-script

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r external-script/requirements.txt

      - name: Run the script to generate saved_tracks.json
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIPY_SCOPE: ${{ secrets.SPOTIPY_SCOPE }}
          SPOTIPY_REFRESH_TOKEN: ${{ secrets.SPOTIPÝ_REFRESH_TOKEN }}
        run: python -u external-script/spotify.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add saved_tracks.json
          git diff --cached --quiet saved_tracks.json || git commit -m "Update saved_tracks.json"
          git push
